#! /bin/sh
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
mount -t sysfs sys /sys
mount -t proc proc /proc
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s
mount /dev/sda /rootfs

echo "" > /proc/sys/kernel/hotplug
umount -f /proc
umount -f /sys

echo "begin to switch rootfs"
exec /sbin/switch_root /rootfs /linuxrc
